---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:4.0.0
    hostname: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888

  zookeeper-2:
    image: confluentinc/cp-zookeeper:4.0.0
    hostname: zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888

  zookeeper-3:
    image: confluentinc/cp-zookeeper:4.0.0
    hostname: zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888

  kafka-1:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9091
      JMX_PORT: 9991
      KAFKA_JMX_OPTS: >
       -Dcom.sun.management.jmxremote
       -Dcom.sun.management.jmxremote.authenticate=false
       -Dcom.sun.management.jmxremote.ssl=false
       -Dcom.sun.management.jmxremote.rmi.port=9991

  kafka-2:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      JMX_PORT: 9992
      KAFKA_JMX_OPTS: >
       -Dcom.sun.management.jmxremote
       -Dcom.sun.management.jmxremote.authenticate=false
       -Dcom.sun.management.jmxremote.ssl=false
       -Dcom.sun.management.jmxremote.rmi.port=9992

  kafka-3:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9093
      JMX_PORT: 9993
      KAFKA_JMX_OPTS: >
       -Dcom.sun.management.jmxremote
       -Dcom.sun.management.jmxremote.authenticate=false
       -Dcom.sun.management.jmxremote.ssl=false
       -Dcom.sun.management.jmxremote.rmi.port=9993

  registry:
    image: confluentinc/cp-schema-registry:4.0.0
    hostname: registry
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'

  rest-proxy:
    image: confluentinc/cp-kafka-rest:4.0.0
    hostname: rest-proxy
    depends_on:
      - registry
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9092,kafka-3:9093
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'

  landoop-topics:
    image: landoop/kafka-topics-ui:latest
    hostname: landoop-topics
    depends_on:
      - rest-proxy
    ports:
      - "8800:8000"
    environment:
      KAFKA_REST_PROXY_URL: http://rest-proxy:8082

  landoop-schemas:
    image: landoop/schema-registry-ui:latest
    hostname: landoop-schemas
    depends_on:
      - rest-proxy
    ports:
      - "8801:8000"
    environment:
      SCHEMAREGISTRY_URL: http://registry:8081

  actors:
    image: fighter-actors:0.1.0
    hostname: actors
    depends_on:
          - registry
    ports:
          - "4200:4200"
    environment:
      KAFKA_BROKERS: kafka-1:9091,kafka-2:9092,kafka-3:9093
      SCHEMA_REGISTRY: http://registry:8081/
      TOPIC_LIST: "ARENAS:1:3,ROUNDS:6:2,RESULTS:6:2,TOKKENS:1:3"