---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.1.2
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999

  registry:
    image: confluentinc/cp-schema-registry:5.1.2
    hostname: registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'OFF'

  app-actors:
    image: fighter-actors:0.2.0-SNAPSHOT
    hostname: actors
    depends_on:
      - registry
    environment:
      KAFKA_BROKERS: kafka:9092
      SCHEMA_REGISTRY: http://registry:8081/
      TOPIC_LIST: "ARENAS,ROUNDS:6:1,REPARTITIONED,TOKKENS,RESULTS-PROC,RESULTS-DSL,EQUIPMENTS"

  app-streamdsl:
    image: fighter-processors:0.2.0-SNAPSHOT
    entrypoint: bin/streams-dsl
    hostname: app-streamdsl
    depends_on:
      - app-actors
    environment:
      APPID: XKE-KSTREAM-DSL
      SCHEMA_REGISTRY: http://registry:8081/
      KAFKA_BROKERS: kafka:9092
      START_LAG: 20
    volumes:
      - ./fighter-processors/src/main/resources/scripts:/opt/docker/scripts/

#  app-processorapi:
#    image: fighter-processors:0.2.0-SNAPSHOT
#    entrypoint: bin/processor-api
#    hostname: app-processorapi
#    depends_on:
#      - app-actors
#    environment:
#      APPID: XKE-KSTREAM-PROC
#      SCHEMA_REGISTRY: http://registry:8081/
#      KAFKA_BROKERS: kafka:9092
#      START_LAG: 20
#    volumes:
#      - ./fighter-processors/src/main/resources/scripts:/opt/docker/scripts/
