---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.0.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
      KAFKA_JMX_OPTS: >
       -Dcom.sun.management.jmxremote
       -Dcom.sun.management.jmxremote.authenticate=false
       -Dcom.sun.management.jmxremote.ssl=false
       -Dcom.sun.management.jmxremote.rmi.port=9999

  registry:
    image: confluentinc/cp-schema-registry:4.0.0
    hostname: registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none

  rest-proxy:
    image: confluentinc/cp-kafka-rest:4.0.0
    hostname: rest-proxy
    depends_on:
      - registry
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'

  actors:
    image: fighter-actors:0.1.0-SNAPSHOT
    hostname: actors
    depends_on:
      - registry
    environment:
      KAFKA_BROKERS: kafka:9092
      SCHEMA_REGISTRY: http://registry:8081/
      TOPIC_LIST: "ARENAS:1:1,ROUNDS:6:1,REPARTITIONED:6:1,TOKKENS:1:1,RESULTS-PROC:1:1,RESULTS-DSL:1:1"

  processors:
    image: fighter-processors:0.1.0-SNAPSHOT
    entrypoint: bin/streams-dsl
    hostname: processors
    depends_on:
      - actors
    environment:
      APPID: XKE-KSTREAM-DSL
      SCHEMA_REGISTRY: http://registry:8081/
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./fighter-processors/src/main/resources/scripts:/opt/docker/scripts/
